atlas:
  - mountPath: /recast_auth
    secret:
      secretName: atlas-auth
      items:
      - key: getkrb.sh
        path: getkrb.sh
        mode: 365 # octal 0555
      - key: getmyproxy.sh
        path: getmyproxy.sh
        mode: 365 # octal 0555
      - key: host.cert
        path: host.cert
        mode: 292 # octal 0444
      - key: gridpw
        path: gridpw
        mode: 256 # ocatal 0400
      - key: kerberos.keytab
        path: kerberos.keytab
        mode: 256 # ocatal 0400
      - key: privkey.pem
        path: privkey.pem
        mode: 256 # ocatal 0400